### ISSUE TITLE
Support Pocketmine 4?

### ISSUE THREAD

**Issue by PocketMiner92** [Kylan1940/HealAndFeed#1]
**PHP Version :**
```Your PHP Version Here```

**Minecraft Version :**
```Your Minecraft Bedrock Version Here```

**HealAndFeed Version :**
```Your HealAndFeed Version Here```

**Describe the error :**
```Describe The Error Here```

**Error Log :**
```The Error Log Here```

**Comment by Kylan1940** [comment]
Yes, please check [the lastest version (2.0.0)](https://github.com/Kylan1940/HealAndFeed)
